Repository VivekRangarajBits/OS-Assignment, pull requests merged in 2022-05, with the labels that each got.

#5 Changing assignment version
  src/main/resources/templates/home.html
Labels: bug

#10 Adding comments
  src/main/java/it/bits/openSource/springbootsample/service/AppInfoService.java
Labels: documentation

#11 Updating comments
  src/main/java/it/bits/openSource/springbootsample/service/AppInfoService.java
Labels: documentation

#12 Update AppInfoService.java
  src/main/java/it/bits/openSource/springbootsample/service/AppInfoService.java
Labels: documentation

#13 Update AppInfoService.java
  src/main/java/it/bits/openSource/springbootsample/service/AppInfoService.java
Labels: documentation

#14 Create group_details.txt
  group_details.txt
Labels: good first issue
